config/routes.rb
Rails.application.routes.draw do
  get 'users_sessions/destroy'

  root 'users#users'
  post 'playlist' => 'playlist#new'
  get 'playlist' => 'playlist#playlist'
  post 'play/:user_id' => 'playlist#play', as: :play
  get 'login' => 'spotify#login'
  get 'auth/spotify/callback' => 'spotify#callback'
  get 'auth/failure' => 'spotify#failure'
  get 'stats' => 'admin#stats'
  get 'percentage' => 'playlist#percentage'

  resources :users_sessions, only: [:destroy]

end

app/controllers/users_controller.rb
require 'rspotify'

class UsersController < ApplicationController
  def users
    users_sessions = UserSession.where(session_id: session[:session_id]).order(:created_at)
    @display_users = users_sessions.collect { |us| DisplayUser.new(us) }
    @alert = flash[:alert]
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_user.html.erb
<li class="row row-flex">
  <div class="col-xs-3 text-center"><%= image_tag(user.image, alt: user.image_alt) %></div>
  <div class="col-xs-7 name">
    <%= user.name %>
  </div>
  <div class="col-xs-2 delete">
    <%= link_to raw('<span aria-hidden="true">&times;</span></button>'), users_session_path(user.id), method: :delete,
                class: 'close', 'aria-label' => 'Delete', data: {confirm: "Are you sure?"} %>
  </div>
</li>

app/views/users/index.html.erb
<h2 class="step">Step 1:
  <small>
    Add at least two persons
    <i class="glyphicon glyphicon-question-sign" data-toggle="popover" data-trigger="hover" data-container="body"
       title="Add persons" data-content="You can add persons by logging in with Spotify
         or by entering your Last.fm user name."></i>
  </small>
</h2>

<div class="jumbotron">
  <ul class="users list-unstyled" id="users">
    <% @users.each do |user| %>
      <%= render partial: 'users/user', locals: {user: user} %>
    <% end %>
    <li class="row-flex new-user">
      <div class="col-sm-2 col-xs-12 user-num">
        <h3>
          <small>#<%= @users.length + 1 %></small>
        </h3>
      </div>
      <div class="col-sm-4 col-xs-12">
        <%= link_to image_tag("spotify_log_in-desktop.png", alt: "Log in with Spotify"), login_path %>
      </div>
      <div class="col-sm-4 col-xs-12">
        <%= form_tag users_sessions_path, :method => 'post', remote: true, id: "new-user-form" do %>
            <%= text_field_tag(:last_fm_username, nil, class: "form-control", placeholder: "Last.fm username") %>
            <%= submit_tag "", :style => "display: none;" %>
        <% end %>
      </div>
    </li>
  </ul>
</div>

<h2>Step 2:
  <small>Get your playlist</small>
</h2>

<%
   disabled = @users.length < 2
   if disabled
%>

    <div data-toggle="popover" data-trigger="hover" data-placement="auto" data-container="body" title="Get playlist"
         data-content="You need to add at least two persons">
      <%=
          link_to "What To-Listen?", playlist_path, class: "btn btn-primary btn-lg btn-block disabled"
      %>
    </div>
<% else %>

    <%=
        link_to "What To-Listen?", playlist_path, class: "btn btn-primary btn-lg btn-block"
    %>

<% end %>

app/views/users/users.html.erb
<div class="instructions">
  <p class="lead"><strong>Welcome to To-Listen</strong>, an application able to create a custom-made playlist for every group of people.<br>
    All you need is to add persons through their <strong>Spotify account</strong> and click
    <strong>What To-Listen?</strong></p>
</div>

<div class="row">
  <div class="col-md-8 users">
    <h2 class="step">Step 1:
      <small>
        Add at least two persons
        <i class="glyphicon glyphicon-question-sign" data-toggle="popover" data-trigger="hover" data-container="body"
           title="Add persons" data-content="You can add persons by logging in with Spotify."></i>
      </small>
    </h2>

    <% if @alert %>
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <strong>Error.</strong> <%= @alert %>
        </div>
    <% end %>

    <div class="jumbotron">
      <ul class="users list-unstyled" id="users">
        <% @display_users.each_with_index { |user, position| %>
            <%= render partial: 'users/user', locals: {user: user, position: position} %>
        <% } %>
        <li class="row row-flex new-user">
          <div class="col-xs-3 user-num text-center">
            #<%= @display_users.length + 1 %>
          </div>
          <div class="col-xs-9">
            <%= link_to image_tag("spotify_log_in-desktop.png", alt: "Log in with Spotify"), login_path, id: 'login' %>
          </div>
        </li>
      </ul>
    </div>
  </div>

  <div class="col-md-4">
    <h2>Step 2:
      <small>Get your playlist</small>
    </h2>

    <div class="playlist-progress hidden"></div>

    <%
       disabled = @display_users.length < 2
       if disabled
    %>

        <div data-toggle="popover" data-trigger="hover" data-placement="auto" data-container="body" title="Get playlist"
             data-content="You need to add at least two persons">
          <%=
              link_to "What To-Listen?", playlist_path, id: 'playlist', class: 'btn btn-primary btn-lg btn-block disabled'
          %>
        </div>
    <% else %>

        <%=
            link_to "What To-Listen?", playlist_path, id: 'playlist', remote: true, method: :post, class: 'btn btn-primary btn-lg btn-block'
        %>

    <% end %>
  </div>
</div>