config/routes.rb
Rails.application.routes.draw do
  get 'users_sessions/destroy'

  root 'users#users'
  post 'playlist' => 'playlist#new'
  get 'playlist' => 'playlist#playlist'
  post 'play/:user_id' => 'playlist#play', as: :play
  get 'login' => 'spotify#login'
  get 'auth/spotify/callback' => 'spotify#callback'
  get 'auth/failure' => 'spotify#failure'
  get 'stats' => 'admin#stats'
  get 'percentage' => 'playlist#percentage'

  resources :users_sessions, only: [:destroy]

end

app/controllers/playlist_controller.rb
require 'rspotify'

class PlaylistController < ApplicationController

  def new
    session_id = session[:session_id]
    session = Session.find(session_id)
    session.generated_playlist = true
    session.save

    job_id = PlaylistWorker.perform_async(session_id)
    render :json => {:job_id => job_id}.to_json
  end

  def playlist
    session_id = session[:session_id]
    session = Session.find_by(id: session_id)
    @tracks = session.track_sessions.order(:position).collect { |ts| ts.track.rspotify_hash }
    @users = session.user_sessions.order(:created_at).collect { |us| DisplayUser.new(us) }
    @warning = flash[:warning]
  end

  def play
    session_id = session[:session_id]
    user_id = params[:user_id]
    user = SpotifyUser.find(user_id)
    user = RSpotify::User.new(user.rspotify_hash)
    playlist = user.create_playlist!(Time.now.utc.localtime.strftime('%F %R - To-Listen'), public: false)

    session = Session.find_by(id: session_id)
    tracks = session.track_sessions.order(:position).collect { |ts| ts.track.rspotify_hash }
    playlist.add_tracks!(tracks)
    redirect_to playlist.external_urls['spotify']
  end

  def percentage
    job_id = params[:job_id]

    if Sidekiq::Status::failed?(job_id)
      render :json => {:status => 'failed', :error => Sidekiq::Status::get(job_id, :error)}.to_json
    elsif Sidekiq::Status::queued?(job_id)
      render :json => {:status => 'queued'}.to_json
    elsif Sidekiq::Status::complete?(job_id)
      warning = Sidekiq::Status::get(job_id, :warning)
      data = Sidekiq::Status::get_all(job_id)
      if (data['total'].to_i == 0)
        percent = 0
      else
        percent = 100 * data['at'].to_i / data['total'].to_i
      end
      message = data['message']

      if warning
        flash[:warning] = warning
      end
      render :json => {:status => 'complete', :percent => percent, :message => message}.to_json
    elsif Sidekiq::Status::working?(job_id)
      data = Sidekiq::Status::get_all(job_id)
      if (data['total'].to_i == 0)
        percent = 0
      else
        percent = 100 * data['at'].to_i / data['total'].to_i
      end
      message = data['message']
      render :json => {:status => 'working', :percent => percent, :message => message}.to_json
    else
      render nothing: true
    end
  end
end

app/helpers/playlist_helper.rb
require 'rspotify'
require 'sidekiq'
require 'sidekiq-status'

module PlaylistHelper

  class SpotifyRecommendUser
    attr_reader :spotify_user, :tracks, :relevances

    # Creates a SpotifyLastFmUser and fetches the songs
    # @param args hash containing :user_session or :spotify_user and last_fm_user
    def initialize(args)
      if !args[:user_session].nil?
        user_session = args[:user_session]
        @spotify_user = RSpotify::User.new(user_session.spotify_user.rspotify_hash) unless user_session.spotify_user.nil?
      else
        @spotify_user = RSpotify::User.new(args[:spotify_user].rspotify_hash) unless args[:spotify_user].nil?
      end
    end

    def tracks
      @tracks ||= fetchTracks
    end

    def calculateRelevances(tracks)
      @relevances = {}
      min = nil
      max = nil

      tracks.each do |t|
        r = relevance(t)
        min = r if min.nil? || r < min
        max = r if max.nil? || r > max
        @relevances.store(t, r)
      end

      old_range = (max - min)
      new_range = 1
      @relevances = Hash[@relevances.map { |k, v| [k, new_value = ((v - min) * new_range) / old_range] }]
    end

    private
    def fetchTracks
      # Fetch spotify tracks
      tracks = []
      threads = []
      unless @spotify_user.nil?
        threads << Thread.new {
          i = 0
          begin
            added_tracks = @spotify_user.saved_tracks(limit: 50, offset: i)
            added_at = @spotify_user.tracks_added_at
            tracks += added_tracks.collect { |o| RelevanceTrack.new(object: o, added_at: added_at[o.id], added_by_user: true) }
            i += 50
          end while added_tracks.count == 50
        }

        j = 0
        playlists = []
        begin
          added_playlists = @spotify_user.playlists(limit: 50, offset: j)
          playlists += added_playlists
          j += 50
        end while added_playlists.count == 50

        playlists.each do |p|
          threads << Thread.new {
            i = 0
            begin
              added_tracks = p.tracks(limit: 100, offset: i)
              added_at = p.tracks_added_at
              added_by = p.tracks_added_by
              tracks += added_tracks.collect { |o| RelevanceTrack.new(object: o, added_at: added_at[o.id], added_by_user: added_by[o.id].id == @spotify_user.id) }
              i += 100
            end while added_tracks.count == 100
          }
        end
      end
      threads.each { |t| t.join }

      tracks
    end

    def relevance(track)
      best = 0
      @tracks.each do |t|
        similarity = t.object.similarity(track)
        time = self.class.time_coefficient(t.added_at)
        mine = t.added_by_user ? 1 : 0
        best = [best, similarity * time * mine].max
      end

      return best
    end

    def self.time_coefficient(date)
      weeks = (Time.now.to_i - date.to_i) / (3600 * 24 * 7).to_f
      [Math.exp(-(weeks-2) / 9), 1].min
    end
  end


  class RelevanceTrack
    attr_reader :object, :added_at, :added_by_user

    def initialize(options)
      @object = options[:object]
      @added_at = options[:added_at]
      @added_by_user = options[:added_by_user]
    end
  end


  class RSpotify::Track

    def ==(o)
      o.class == self.class && o.state == state
    end

    def hash
      state.hash
    end

    def similarity(o)
      return 1 if self == o
      return 0.33 if self.artists == o.artists
      return 0.17 if self.artists.product(o.artists).any? { |a1, a2| a1 == a2 }
      0
    end

    def to_s
      @artists.join(',') + ' - ' + @name
    end

    alias_method :eql?, :==

    protected
    def state
      [@name, @artists]
    end
  end

  class RSpotify::Artist

    def ==(o)
      o.class == self.class && o.state == state
    end

    def hash
      state.hash
    end

    def to_s
      @name
    end

    alias_method :eql?, :==

    protected
    def state
      @name
    end
  end
end

app/views/playlist/_track.html.erb
<%
   artists = track.artists.first.name
   title = track.name
   image = track.album.images.last['url']
   alt = track.album.name + ' cover image'
%>

<li class="row row-flex">
  <div class="col-sm-1 col-xs-2 hidden-xs">
    #<%= position %>
  </div>
  <div class="col-sm-2 col-xs-3 image">
    <%= image_tag image, alt: alt %>
  </div>
  <div class="col-sm-9 col-xs-7">
    <div class="row row-flex">
      <div class="col-sm-6 col-xs-12 col-sm-push-6 title">
        <%= title %>
      </div>
      <div class="col-sm-6 col-xs-12 col-sm-pull-6">
        <%= artists %>
      </div>
    </div>
  </div>
</li>

app/views/playlist/playlist.html.erb
<h2>Playlist</h2>

<div class="text-center play">
  <%= content_tag :a, image_tag('spotify_listen-desktop.png', alt: 'Listen on Spotify'), {id: 'play', type: 'button', 'data-toggle' => 'modal', 'data-target' => '#usersModal'} %>
</div>

<% if @warning %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>Warning!</strong> <%= @warning %>
    </div>
<% end %>

<div class="create-playlist hidden">
  <h3>Create playlist in:</h3>
  <ul class="row row-flex users-playlist list-unstyled">
    <% @users.each do |user| %>
        <li class="col-md-2 col-xs-6 text-center">
          <div><%= link_to image_tag(user.image, alt: user.image_alt), play_path(user.spotify_id), method: :post, class: 'user' %></div>
          <div><%= user.name %></div>
        </li>
    <% end %>
  </ul>
</div>

<div class="jumbotron">
  <ul class="list-unstyled tracks">
    <% @tracks.each_with_index do |track, index| %>
        <%= render partial: 'playlist/track', locals: {track: track, position: index + 1} %>
    <% end %>
  </ul>
</div>